version = 0.1
[default.deploy.parameters]
stack_name = "chaos-lambda-samples"
resolve_s3 = true
s3_prefix = "chaos-lambda-samples"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ChaosLayerARN=\"arn:aws:lambda:us-east-1:871265522301:layer:chaos-lambda-extension-x86_64-unknown-linux-gnu-release:12\""
image_repositories = []
